#define HAVE_X86_INLINE_ASM 0
#define HAVE_MMX 1
#define ARCH_X86 1
#define SYS_WINDOWS 1
#define STACK_ALIGNMENT 32
#define HAVE_WIN32THREAD 1
#define HAVE_THREAD 1
#define HAVE_LOG2F 1
#define HAVE_VECTOREXT 1
#define fseek _fseeki64
#define ftell _ftelli64
#define HAVE_GPL 1
#define HAVE_INTERLACED 1
#define HAVE_MALLOC_H 1
#define HAVE_ALTIVEC 0
#define HAVE_ALTIVEC_H 0
#define HAVE_ARMV6 0
#define HAVE_ARMV6T2 0
#define HAVE_NEON 0
#define HAVE_BEOSTHREAD 0
#define HAVE_POSIXTHREAD 0
#define HAVE_SWSCALE 0
#define HAVE_LAVF 0
#define HAVE_FFMS 0
#define HAVE_GPAC 0
#define HAVE_AVS 0
#define HAVE_CPU_COUNT 0
#define HAVE_OPENCL 0
#define HAVE_THP 0
#define HAVE_LSMASH 0
#define HAVE_AS_FUNC 0
#define HAVE_INTEL_DISPATCHER 0
#define HAVE_MSA 0
#define HAVE_MMAP 0
#define HAVE_WINRT 0
#if _MSC_VER
#define HAVE_AVX 0
#define HAVE_AVX2 0
#else
#define HAVE_AVX 1
#define HAVE_AVX2 1
#endif