#ifndef MK1MF_BUILD
    /* auto-generated by util/mkbuildinf.pl for crypto/cversion.c */
    #define CFLAGS cflags
    /*
     * Generate CFLAGS as an array of individual characters. This is a
     * workaround for the situation where CFLAGS gets too long for a C90 string
     * literal
     */
    static const char cflags[] = {
        'c','o','m','p','i','l','e','r',':',' ','a','a','r','c','h','6','4','-',
        'l','i','n','u','x','-','a','n','d','r','o','i','d','-','g','c','c',' ',
        '-','I','.',' ','-','I','.','.',' ','-','I','.','.','/','i','n','c','l',
        'u','d','e',' ',' ','-','D','Z','L','I','B','_','S','H','A','R','E','D',
        ' ','-','D','Z','L','I','B',' ','-','D','O','P','E','N','S','S','L','_',
        'T','H','R','E','A','D','S',' ','-','D','_','R','E','E','N','T','R','A',
        'N','T',' ','-','D','D','S','O','_','D','L','F','C','N',' ','-','D','H',
        'A','V','E','_','D','L','F','C','N','_','H',' ','-','O','3',' ','-','W',
        'a','l','l',' ','-','D','S','H','A','1','_','A','S','M',' ','-','D','S',
        'H','A','2','5','6','_','A','S','M',' ','-','D','S','H','A','5','1','2',
        '_','A','S','M','\0'
    };
    #define PLATFORM "platform: linux-aarch64"
    #define DATE "built on: Sun Jul 31 21:14:01 2022"
#endif
